"""Template-based feature synthesis.

Every generated feature is a self-contained module exposing:
  FEATURE: dict of metadata
  run(items, params=None) -> dict

Templates are deterministic: the same plan always yields the same code.
All plan parameters are emitted through repr(), never string interpolation,
so hostile gap text cannot break out of the template.
"""
from __future__ import annotations

import textwrap
from typing import Any

from .plans import Candidate, FeaturePlan
from .safety import validate_source

_HEADER = '''"""Auto-generated by the Sugarcode self-improvement engine.

Module: {module_slug}
Gap: {gap_signature}
Do not hand-edit; regenerate through the engine instead.
"""

import json
import re

FEATURE = {feature_meta!r}

'''


def _meta(plan: FeaturePlan) -> dict[str, Any]:
    return {
        "name": plan.name, "kind": plan.kind, "module": plan.module_slug,
        "description": plan.description, "gap_signature": plan.gap_signature,
        "version": 1, "generated_by": "sugarcode-self-improve",
    }


def _keyword_filter(plan: FeaturePlan) -> str:
    body = '''
_KEYWORDS = {keywords!r}
_MODE = {mode!r}


def _text_of(item):
    if isinstance(item, str):
        return item
    return json.dumps(item, sort_keys=True, default=str)


def run(items, params=None):
    """Keep (or drop) items whose text mentions any configured keyword."""
    params = params or {{}}
    keywords = list(params.get("keywords", _KEYWORDS))
    mode = params.get("mode", _MODE)
    if mode not in ("keep", "drop"):
        raise ValueError("mode must be 'keep' or 'drop'")
    needles = [k.lower() for k in keywords]
    kept, removed = [], []
    for item in items:
        hit = any(n in _text_of(item).lower() for n in needles)
        (kept if (hit if mode == "keep" else not hit) else removed).append(item)
    return {{"items": kept, "removed": removed, "count": len(kept)}}
'''.format(keywords=list(plan.params.get("keywords", [])), mode=plan.params.get("mode", "keep"))
    return _HEADER.format(module_slug=plan.module_slug, gap_signature=plan.gap_signature, feature_meta=_meta(plan)) + body


def _scoring_rule(plan: FeaturePlan) -> str:
    body = '''
_WEIGHTS = {weights!r}
_THRESHOLD = {threshold!r}


def _text_of(item):
    if isinstance(item, str):
        return item
    return json.dumps(item, sort_keys=True, default=str)


def score_item(item, weights=None):
    weights = weights or _WEIGHTS
    low = _text_of(item).lower()
    return sum(float(w) for kw, w in weights.items() if str(kw).lower() in low)


def run(items, params=None):
    """Score each item by weighted keyword hits and select over threshold."""
    params = params or {{}}
    weights = dict(params.get("weights", _WEIGHTS))
    threshold = float(params.get("threshold", _THRESHOLD))
    scored = [{{"item": it, "score": score_item(it, weights)}} for it in items]
    for row in scored:
        row["selected"] = row["score"] >= threshold
    scored.sort(key=lambda r: (-r["score"], _text_of(r["item"])))
    return {{"scored": scored, "selected": [r["item"] for r in scored if r["selected"]],
            "threshold": threshold}}
'''.format(weights=dict(plan.params.get("weights", {})), threshold=float(plan.params.get("threshold", 1.0)))
    return _HEADER.format(module_slug=plan.module_slug, gap_signature=plan.gap_signature, feature_meta=_meta(plan)) + body


def _text_transform(plan: FeaturePlan) -> str:
    body = '''
_PATTERN = {pattern!r}
_REPLACEMENT = {replacement!r}


def run(items, params=None):
    """Apply a regex substitution to every string item; pass others through."""
    params = params or {{}}
    pattern = re.compile(params.get("pattern", _PATTERN))
    replacement = params.get("replacement", _REPLACEMENT)
    out, changed = [], 0
    for item in items:
        if isinstance(item, str):
            new = pattern.sub(replacement, item)
            if new != item:
                changed += 1
            out.append(new)
        else:
            out.append(item)
    return {{"items": out, "changed": changed}}
'''.format(pattern=str(plan.params.get("pattern", r"\s+")), replacement=str(plan.params.get("replacement", " ")))
    return _HEADER.format(module_slug=plan.module_slug, gap_signature=plan.gap_signature, feature_meta=_meta(plan)) + body


def _aggregator(plan: FeaturePlan) -> str:
    body = '''
_GROUP_BY = {group_by!r}
_OP = {op!r}
_VALUE_FIELD = {value_field!r}


def run(items, params=None):
    """Group dict items by a field and aggregate (count, sum, or mean)."""
    params = params or {{}}
    group_by = params.get("group_by", _GROUP_BY)
    op = params.get("op", _OP)
    value_field = params.get("value_field", _VALUE_FIELD)
    if op not in ("count", "sum", "mean"):
        raise ValueError("op must be count, sum, or mean")
    groups = {{}}
    for item in items:
        if not isinstance(item, dict):
            continue
        key = str(item.get(group_by, "<missing>"))
        groups.setdefault(key, []).append(item)
    result = {{}}
    for key, rows in groups.items():
        if op == "count":
            result[key] = len(rows)
        else:
            vals = [float(r[value_field]) for r in rows
                    if isinstance(r.get(value_field), (int, float))]
            if op == "sum":
                result[key] = sum(vals)
            else:
                result[key] = (sum(vals) / len(vals)) if vals else None
    return {{"groups": result, "group_by": group_by, "op": op,
            "ungrouped": len(items) - sum(len(v) for v in groups.values())}}
'''.format(group_by=str(plan.params.get("group_by", "category")), op=str(plan.params.get("op", "count")),
           value_field=str(plan.params.get("value_field", "value")))
    return _HEADER.format(module_slug=plan.module_slug, gap_signature=plan.gap_signature, feature_meta=_meta(plan)) + body


def _threshold_alert(plan: FeaturePlan) -> str:
    body = '''
_FIELD = {field!r}
_THRESHOLD = {threshold!r}
_DIRECTION = {direction!r}


def _num(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def run(items, params=None):
    """Flag dict items whose numeric field crosses a threshold."""
    params = params or {{}}
    field = params.get("field", _FIELD)
    threshold = float(params.get("threshold", _THRESHOLD))
    direction = params.get("direction", _DIRECTION)
    if direction not in ("above", "below"):
        raise ValueError("direction must be above or below")
    flagged, clear, skipped = [], [], 0
    for item in items:
        value = _num(item.get(field)) if isinstance(item, dict) else None
        if value is None:
            skipped += 1
            continue
        hit = value >= threshold if direction == "above" else value <= threshold
        (flagged if hit else clear).append({{"item": item, "value": value}})
    return {{"flagged": flagged, "clear": clear, "skipped": skipped,
            "field": field, "threshold": threshold, "direction": direction}}
'''.format(field=str(plan.params.get("field", "value")), threshold=float(plan.params.get("threshold", 0.0)),
           direction=str(plan.params.get("direction", "above")))
    return _HEADER.format(module_slug=plan.module_slug, gap_signature=plan.gap_signature, feature_meta=_meta(plan)) + body


def _field_extractor(plan: FeaturePlan) -> str:
    body = '''
_FIELDS = {fields!r}


def run(items, params=None):
    """Extract named regex captures from string items."""
    params = params or {{}}
    fields = {{name: re.compile(pat) for name, pat in
              dict(params.get("fields", _FIELDS)).items()}}
    records, matched = [], 0
    for item in items:
        if not isinstance(item, str):
            continue
        extracted = {{}}
        for name, pattern in fields.items():
            m = pattern.search(item)
            if m:
                extracted[name] = m.group(1) if m.groups() else m.group(0)
        if extracted:
            matched += 1
        records.append({{"text": item, "extracted": extracted}})
    return {{"records": records, "matched_count": matched}}
'''.format(fields=dict(plan.params.get("fields", {})))
    return _HEADER.format(module_slug=plan.module_slug, gap_signature=plan.gap_signature, feature_meta=_meta(plan)) + body


_BUILDERS = {
    "keyword_filter": _keyword_filter,
    "scoring_rule": _scoring_rule,
    "text_transform": _text_transform,
    "aggregator": _aggregator,
    "threshold_alert": _threshold_alert,
    "field_extractor": _field_extractor,
}


def synthesize_code(plan: FeaturePlan) -> str:
    source = textwrap.dedent(_BUILDERS[plan.kind](plan))
    validate_source(source)
    return source
