"""Module registry: every SugarCode AI module, its sub-network and lifecycle state.

The nine sub-networks are assigned from the module themes in the spec doc
(the doc states "nine functional sub-networks" without naming them).
"""
from __future__ import annotations
from dataclasses import dataclass, field


@dataclass(frozen=True)
class ModuleSpec:
    slug: str
    name: str
    subnetwork: str
    summary: str
    status: str = "specified"  # specified | thin | verified
    notes: str = ""


SUBNETWORKS: dict[str, str] = {
    "core-intelligence": "Central reasoning, dashboard and literature engines",
    "genome-editing": "Genomic analysis and CRISPR/variant design",
    "protein-engineering": "Structure prediction, docking and de novo design",
    "synthetic-biology": "Circuits, pathways, promoters and biofoundry",
    "cellular-systems": "Cell/tissue simulation and imaging",
    "therapeutics": "Clinical, oncology and personalized-medicine engines",
    "microbiome-phage": "Microbial community and phage design",
    "fabrication-evolution": "Bioprinting, chemistry and evolutionary sandboxes",
    "platform": "Stats, enterprise tiers, SDK and support",
}

_VERIFIED = {"neuro_hub", "gene_explorer", "crispr_opt", "codon_opt", "prime_design",
             "deepsplice", "str_scope", "rna_decoder", "promoter_lib", "dark_genome",
             "virtual_cell", "synbio_studio", "living_computer", "omega_stats",
             "ecosystem", "dna_to_code",
             "gene_analysis", "crispr_cargo", "crispr_muse", "epi_edit", "openclinvar",
             "genomegpt", "alpha_fold_ui", "docking_studio", "evofold_4d", "mutdock",
             "protein_painter"}

_MODULES: list[tuple[str, str, str, str]] = [
    # slug, name, subnetwork, summary
    ("neuro_hub", "Neuro-Hub (Dashboard)", "core-intelligence",
     "Central command center: global compute flux, unified search across the module stack, platform-wide health."),
    ("bio_copilot", "Bio-Copilot", "core-intelligence",
     "AI-native research assistant grounded in PubMed data; mutation-to-phenotype reasoning; FASTA/PDB outputs; CRISPR design; SBML simulation; FBA; docking; executable notebooks."),
    ("synbio_wizard", "SynBio Wizard", "core-intelligence",
     "Guided synthetic-biology compiler: goal definition to pathway design, chassis selection, feasibility and assembly recommendations."),
    ("neuro_pipeline", "Neuro-Pipeline", "core-intelligence",
     "Neuro-symbolic MLOps: continual learning, circuit-level explainability, virtual lesion studies, hybrid simulation-learning loops."),
    ("biogpt_lit", "BioGPT Lit", "core-intelligence",
     "Self-indexing scientific reasoning engine: entity/relationship extraction into a temporal knowledge graph, contradiction detection, hypothesis generation."),
    ("chemgpt_engine", "ChemGPT Engine", "fabrication-evolution",
     "Generative-predictive molecular design: ADMET profiles, LogP/solubility, retrosynthesis, Pareto multi-objective optimization."),
    ("genomegpt", "GenomeGPT", "core-intelligence",
     "Genomic sequence model: regulatory motifs, chromatin-loop interactions, clinical variant interpretation of long-range dependencies."),
    ("gene_analysis", "Gene Analysis", "genome-editing",
     "Multi-omic gene deep-dive integrating NCBI/UniProt/ClinVar-style data: summaries, pathways, variant impact, CRISPR targets."),
    ("gene_explorer", "Gene Explorer", "genome-editing",
     "Central-dogma mapper: DNA -> mRNA -> protein with sequence segments, transcripts and amino-acid annotations."),
    ("crispr_opt", "CRISPR Opt", "genome-editing",
     "gRNA design optimizing on-target efficiency and off-target risk; PAM-site and regulatory-track visualization data."),
    ("crispr_cargo", "CRISPR Cargo", "genome-editing",
     "Delivery-system optimization: LNP/AAV serotype selection per payload and tissue, pharmacokinetic concentration models."),
    ("crispr_muse", "CRISPR Muse", "genome-editing",
     "RL-style gRNA generator refined through simulated lab feedback loops; multi-PAM compatibility."),
    ("epi_edit", "Epi-Edit", "genome-editing",
     "Epigenome engineering via CRISPRa/i: chromatin landscape, histone marks and accessibility modeling."),
    ("prime_design", "Prime Design", "genome-editing",
     "pegRNA design for prime editing: PBS and RT-template optimization, nicking sites, off-target scans."),
    ("dark_genome", "Dark Genome", "genome-editing",
     "Non-coding DNA decoder: hidden enhancers, functional RNA elements, regulatory-landscape mapping."),
    ("rna_decoder", "RNA Decoder", "genome-editing",
     "Epitranscriptomics: m6A prediction from sequence, modification maps, mRNA optimization for stability/expression."),
    ("deepsplice", "DeepSplice", "genome-editing",
     "Variant effect on alternative splicing: splice-site strength PWMs, isoform consequence description."),
    ("openclinvar", "OpenClinVar", "genome-editing",
     "Explainable ClinVar-style variant interpretation: plain-language pathogenicity, clinical summaries."),
    ("str_scope", "STR-Scope", "genome-editing",
     "Short tandem repeat analytics: repeat-expansion biomarkers, diagnostic potential index."),
    ("codon_opt", "Codon Opt", "genome-editing",
     "Codon optimization balancing expression and host metabolic load: CAI/CHI, GC windows, tRNA-pool (TASEP) simulation, FBA coupling."),
    ("alpha_fold_ui", "AlphaFold UI", "protein-engineering",
     "Protein structure prediction interface: 3D coordinates, pLDDT confidence, PAE, PDB download."),
    ("docking_studio", "Docking Studio", "protein-engineering",
     "Protein-ligand binding affinity prediction, binding-pocket residues, virtual screening support."),
    ("evofold_4d", "EvoFold 4D", "protein-engineering",
     "Conformational-transition dynamics: open/closed states, PTM and ligand effects, temporal traces."),
    ("mutdock", "MutDock", "protein-engineering",
     "Mutation effect on drug affinity: resistance hotspots, cross-drug resistance forecast."),
    ("protein_painter", "Protein Painter", "protein-engineering",
     "De novo protein design from functional descriptions with fold verification and stability prediction."),
    ("bio_material", "Bio-Material", "synthetic-biology",
     "Synthetic biomaterial design: polymer-production pathways, degradation modeling, structure-function prediction."),
    ("synbio_studio", "Syn-Bio Studio", "synthetic-biology",
     "Visual genetic logic-circuit builder with ODE-based dynamics: oscillators, switches, sensors."),
    ("metabodesigner", "MetaboDesigner", "synthetic-biology",
     "Novel metabolic pathway design: enzyme/reaction identification, FBA bottleneck analysis, precursor cost."),
    ("promoter_lib", "Promoter Lib", "synthetic-biology",
     "Synthetic promoter libraries with predictable strengths and TF compatibility; motif heatmaps."),
    ("synthetic_life", "Synthetic Life", "synthetic-biology",
     "Minimal genome design: essential gene sets, knockout lethality, metabolic requirements of minimal life."),
    ("biofactory_1_a", "BioFactory 1-A", "synthetic-biology",
     "Automated robotic protocol generation for high-throughput experimentation; equipment and optimization tips."),
    ("robotic_flow", "Robotic Flow", "synthetic-biology",
     "Lab-automation control: transformation/plating coordination, real-time monitoring, precision execution."),
    ("syn_stab_ai", "Syn-Stab AI", "synthetic-biology",
     "Evolutionary stability prediction for synthetic circuits: failure risk from burden/drift, half-life improvements."),
    ("cell_free_opt", "Cell-Free Opt", "synthetic-biology",
     "CFPS optimization: reagent concentrations for yield, reaction-kinetics simulation, cost calculation."),
    ("stability_ai", "Stability AI", "synthetic-biology",
     "Genetic/phenotypic stability forecast: plasmid loss, mutational drift over generations, stability scores."),
    ("living_computer", "Living Computer", "synthetic-biology",
     "Cellular logic compiler: logic operations mapped to genetic parts, signal propagation and stochastic noise analysis."),
    ("bio_switch", "Bio-Switch", "synthetic-biology",
     "Molecular biosensor design: binding domains coupled to reporters for metabolite/toxin/biomarker detection."),
    ("phageforge", "PhageForge", "cellular-systems",
     "CRISPR-payload bacteriophage engineering against multi-drug-resistant pathogens; host targeting."),
    ("cell_twin", "Cell-Twin", "cellular-systems",
     "Patient-cell digital twins from multi-omic data; in silico drug trials with apoptosis/proliferation readouts."),
    ("fate_predictor", "Fate Predictor", "cellular-systems",
     "Direct reprogramming predictor: required TFs and protocols between cell types with success rates."),
    ("cellfatenet", "CellFateNet", "cellular-systems",
     "Causal regulatory-network visualization of differentiation; stepwise genetic recipes for transformation."),
    ("organoid_ai", "Organoid AI", "cellular-systems",
     "Patient-derived organoid design/simulation: growth conditions, media recipes, spatial expression, drug response."),
    ("virtual_cell", "Virtual Cell", "cellular-systems",
     "Multi-scale cell simulator: FBA + gene-regulatory integration, growth/expression/phenotype prediction."),
    ("bioimage_ai", "BioImage AI", "cellular-systems",
     "Microscopy computer vision: cell counting, morphology assessment, segmentation correction."),
    ("cellpainter", "CellPainter", "cellular-systems",
     "Multiplex fluorescent imaging signatures: morphological fingerprints of drugs/mutations."),
    ("cellpainter_4d", "CellPainter 4D", "cellular-systems",
     "Temporal cell-morphology simulation: event timelines and morphological-drift traces."),
    ("syndroid", "SynDroid", "cellular-systems",
     "Minimal synthetic-cell simulator: emergent behavior from essential gene sets."),
    ("tissue_eng", "Tissue Eng", "cellular-systems",
     "3D bioprinting strategies: biomaterials, cell types, vascularization, mechanical-response simulation."),
    ("infinite_diagnosis", "Infinite Diagnosis", "therapeutics",
     "Cross-domain literature reasoning for non-standard breakthroughs; diagnostic clusters and roadmaps."),
    ("car_t_designer", "CAR-T Designer", "therapeutics",
     "CAR construct optimization: scFv/signaling elements per antigen, toxicity prediction, trial simulation."),
    ("living_tx", "Living Tx", "therapeutics",
     "Engineered probiotic therapeutics: strain selection, modifications, gut-microbiome impact simulation."),
    ("neohunter", "NeoHunter", "therapeutics",
     "Personalized neoantigen identification: immunogenicity ranking, HLA binding prediction."),
    ("gene_tx_opt", "Gene-Tx Opt", "therapeutics",
     "Gene-therapy vector optimization: tissue-specific promoters/capsids, delivery simulation."),
    ("vector_opt", "Vector Opt", "therapeutics",
     "Viral capsid fine-tuning: capsid-receptor docking, neutralizing-antibody impact, transduction efficiency."),
    ("organoid_screen", "Organoid Screen", "therapeutics",
     "Virtual drug screening on organoid models: efficacy, biomarkers, synergy scores."),
    ("neuroplan_ai", "NeuroPlan AI", "therapeutics",
     "Neurosurgical planning: MRI segmentation + tractography, safest-path mapping, NeuroTwin risk scores."),
    ("neodti_engine", "NeoDti Engine", "therapeutics",
     "Drug repurposing via graph learning on drug-target interactions; Therapeutic Resilience Index."),
    ("liquid_biopsy", "Liquid Biopsy", "therapeutics",
     "ctDNA detection with deep-learning noise filters; biomarker selection, raw vs filtered signal."),
    ("rarenet_ai", "RareNet AI", "therapeutics",
     "Rare-disease diagnostic reasoning over symptoms + multi-omics with explainable confidence."),
    ("oncocircuit", "OncoCircuit", "therapeutics",
     "Cancer-targeting synthetic circuits: tumor-specific promoters, logic-gated therapeutic triggers."),
    ("pdx_insight", "PDX Insight", "therapeutics",
     "PDX model monitoring: Model Fidelity Index, translational drift, CRISPR restoration strategies."),
    ("microaiverse", "MicroAiverse", "microbiome-phage",
     "Cultivation solver for unculturable microbes: media recipes, co-culture partners from metabolic flux."),
    ("microbiome_exp", "Microbiome Exp", "microbiome-phage",
     "16S rRNA taxonomic analysis: diversity indices, distributions, functional potential."),
    ("micro_tx", "Micro-Tx", "microbiome-phage",
     "Microbiome therapeutics: microbe-prebiotic pairing for metabolic disorders with community simulation."),
    ("microbiome_rx", "Microbiome Rx", "microbiome-phage",
     "Microbial-community metabolic interaction simulation: diet/antibiotic effects on metabolite flux."),
    ("riboswitch", "Riboswitch", "microbiome-phage",
     "RNA biosensor design: metabolite-responsive conformational switches, 2D structure, response curves."),
    ("phage_tx", "Phage-Tx", "microbiome-phage",
     "Phage-therapy efficacy model: phage-bacteria coevolution, cocktail optimization."),
    ("phage_designer", "Phage Designer", "microbiome-phage",
     "Phage host-range/payload engineering: genome modification, cloning strategies, sequence analysis."),
    ("bioprint_pro", "BioPrint Pro", "fabrication-evolution",
     "Bioprinting calibration: ink rheology, pressure, crosslinking kinetics, structural-integrity prediction."),
    ("bioplayground", "BioPlayground", "fabrication-evolution",
     "Evolutionary sandbox: selective pressures, population drift, robustness testing of engineered systems."),
    ("dna_to_code", "DNA-to-Code", "fabrication-evolution",
     "Biology-to-Python analogy layer: molecular mechanisms rendered as software architecture."),
    ("biosimvr", "BioSimVR", "fabrication-evolution",
     "Simulated 3D virtual-laboratory experiment runner with observations and conclusions."),
    ("synlife_evo", "SynLife Evo", "fabrication-evolution",
     "Long-term evolutionary simulation of synthetic organisms over thousands of generations."),
    ("omega_stats", "Omega Stats", "platform",
     "Platform performance dashboard: prediction accuracy, efficiency rates, throughput across sub-networks."),
    ("enterprise_bio", "Enterprise Bio", "platform",
     "Computational tier breakdown: academic to industrial access levels, private data vaults."),
    ("ecosystem", "Ecosystem", "platform",
     "Documentation and SDK hub: programmatic access snippets, plugin architecture, standards."),
    ("nexus_support", "Nexus Support", "platform",
     "Communication node: inquiries, custom AI build requests, technical support routing."),
]

REGISTRY: dict[str, ModuleSpec] = {}
for slug, name, subnet, summary in _MODULES:
    assert subnet in SUBNETWORKS, subnet
    status = "verified" if slug in _VERIFIED else "specified"
    REGISTRY[slug] = ModuleSpec(slug=slug, name=name, subnetwork=subnet, summary=summary, status=status)


def module_slugs(subnetwork: str | None = None) -> list[str]:
    if subnetwork is None:
        return list(REGISTRY)
    return [s for s, m in REGISTRY.items() if m.subnetwork == subnetwork]
