"""AUTHORED, NOT RUN. G03: codegen._assemble must render the Module:/Gap: header fields through
self_improve.header_text (json.dumps ensure_ascii, one line, no validation)."""
import ast

import pytest

from sugarcode.self_improve.codegen import synthesize_code
from sugarcode.self_improve.header_text import encode_header_text
from sugarcode.self_improve.plans import CAPABILITY_KINDS, FeaturePlan
from sugarcode.self_improve.safety import validate_source

HOSTILE = [
    '"""\nimport os\nos.system("x")\n"""', '"""', 'a"""b', "\\", "a\nb", "a\r\nb", "a\u2028b", "a\u2029b",
    "{x} {0} %s {feature_meta!r}", "# c", "\x00\x1f", "\ud800", "\U0001f642",
]
UNICODE_OK = ["módulo", "中文", "Démo_1"]


def plan(slug="m1", sig="gap sig", kind="keyword_filter"):
    return FeaturePlan(module_slug=slug, name="auto_x", kind=kind, description="d", gap_signature=sig, params={})


def header_lines(src):
    lines = src.split("\n")
    return lines, [l for l in lines if l.startswith("Module: ")], [l for l in lines if l.startswith("Gap: ")]


def test_benign_header_lines_are_json_encoded():
    lines, mod, gap = header_lines(synthesize_code(plan("opportunity-discovery", "filter only biology grants")))
    assert lines[0] == '"""Auto-generated by the Sugarcode self-improvement engine.'
    assert lines[2] == 'Module: "opportunity-discovery"'
    assert lines[3] == 'Gap: "filter only biology grants"'
    assert lines[4] == "Do not hand-edit; regenerate through the engine instead."
    assert lines[5] == '"""'


@pytest.mark.parametrize("sig", HOSTILE + UNICODE_OK + [""])
def test_hostile_or_unicode_signature_stays_one_header_line(sig):
    src = synthesize_code(plan(sig=sig))
    lines, mod, gap = header_lines(src)
    assert mod == ['Module: "m1"']
    assert gap == ["Gap: " + encode_header_text(sig)]
    assert lines[5] == '"""' and lines[4].startswith("Do not hand-edit")
    assert "import os" not in [l.strip() for l in lines]
    ast.parse(src)
    validate_source(src)


@pytest.mark.parametrize("slug", HOSTILE + UNICODE_OK + ["../escape", "---", ""])
def test_hostile_or_unicode_slug_stays_one_header_line(slug):
    src = synthesize_code(plan(slug=slug))
    lines, mod, gap = header_lines(src)
    assert mod == ["Module: " + encode_header_text(slug)]
    assert gap == ['Gap: "gap sig"']
    assert lines[5] == '"""'
    assert "import os" not in [l.strip() for l in lines]
    validate_source(src)


@pytest.mark.parametrize("kind", sorted(CAPABILITY_KINDS))
def test_every_kind_with_hostile_header_fields(kind):
    src = synthesize_code(plan(slug=HOSTILE[0], sig=HOSTILE[0], kind=kind))
    validate_source(src)
    assert len(header_lines(src)[1]) == 1 and len(header_lines(src)[2]) == 1


@pytest.mark.parametrize("sig", HOSTILE + UNICODE_OK + [""])
def test_feature_metadata_still_carries_the_raw_values(sig):
    src = synthesize_code(plan(slug="módulo", sig=sig))
    ns = {}
    exec(compile(src, "<t>", "exec"), ns)
    assert ns["FEATURE"]["gap_signature"] == sig
    assert ns["FEATURE"]["module"] == "módulo"


def test_generation_is_deterministic():
    assert synthesize_code(plan(sig="a\u2028b")) == synthesize_code(plan(sig="a\u2028b"))
